"use server";

import { GoogleGenAI, Modality } from "@google/genai";
import assert from "node:assert";
import { rateLimit } from "@/utils/rate-limiter";
import { getSession } from "next-auth/react";
import { getServerSession } from "next-auth";

// Prompt for Gemini
const VISITING_CARD_PROMPT = `
Generate a professional horizontal visiting card with these specifications:

1. LAYOUT:
   - Left-aligned text content (70% width)
   - Right-side reserved for QR code/social icons (30% width)

2. DESIGN FRAMEWORK:
   - Background: [User's color preference] gradient (default: deep navy blue)
   - Text: High-contrast color (white/light for dark backgrounds, dark for light)
   - Accent: Thin divider line in complementary color

3. CONTENT STRUCTURE:
   [NAME] (Bold, largest font)
   ━━━━━━━━━━━━━ (Thin accent line)
   [TITLE] | [COMPANY] (Medium font)
   [TAGLINE] (Italic, smaller font if provided)

   [PHONE] • [EMAIL]
   [WEBSITE] • [SOCIAL MEDIA HANDLES]

4. RIGHT-SIDE ELEMENTS:
   - QR code linking to [PRIMARY URL]
   - Minimalist social media icons (if provided)

5. STYLE CONSTRAINTS:
   - Max 2 font families
   - Subtle texture/pattern at <10% opacity
   - 300 DPI resolution
   - Always maintain negative space

Corporate visiting card, ultra-detailed, 8k, studio lighting, minimalist, professional
`;

export async function createDesign(_: unknown, formData: FormData) {
  try {
    const session = await getServerSession();
    // console.log("session", session);
    if (!session) throw new Error("Unauthorized");

    // Rate limiting: 5 requests per minute per user
    const { success, message, remaining, reset } = await rateLimit({
      key: `user:${session?.user?.email}`,
      limit: 5,
      windowInSeconds: 60,
    });

    if (!success) {
      return {
        success: false,
        message,
        imageData: null,
      };
    }

    const userInput = formData.get("message")?.toString() || "";
    assert(userInput.length > 0, "Please enter a description");
    assert(process.env.GEMINI_KEY, "GEMINI_KEY is missing in env");

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_KEY });
    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash-preview-image-generation",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `${VISITING_CARD_PROMPT}\n\nUSER REQUIREMENTS:\n${userInput}`,
            },
          ],
        },
      ],
      config: { responseModalities: [Modality.TEXT, Modality.IMAGE] },
    });

    const parts = response?.candidates?.[0]?.content?.parts;
    if (!parts?.length) throw new Error("No content generated by Gemini");

    let textResponse = "";
    let imageBase64 = "";

    for (const part of parts) {
      if (part.text) {
        textResponse = part.text;
      } else if (part.inlineData?.data) {
        imageBase64 = part.inlineData.data;
      }
    }

    if (!imageBase64) throw new Error("No image generated");

    return {
      success: true,
      message: textResponse || "Visiting card generated successfully",
      imageData: `data:image/png;base64,${imageBase64}`,
      meta: {
        rateLimit: { remaining, reset },
      },
    };
  } catch (error) {
    console.error("Generation error:", error);
    return {
      success: false,
      message: (error as Error).message || "Generation failed",
      imageData: null,
    };
  }
}
